language: node_js
node_js:
  - 16

# installing required items for build
install:
  - npm install -g yarn

 # testing script

 # notify codecov and deploy to cloud
after_success:
  bash <(curl -s https://codecov.io/bash);

branches:
  only:
    - master
    - main